#+TITLE:        Логическое программирование
#+AUTHOR:       Кевролетин В.В. группа с8403а(246)
#+EMAIL:        kevroletin@gmial.com
#+LANGUAGE:     russian
#+LATEX_HEADER: \usepackage[cm]{fullpage}

* Задание 12
** Условие

(5.3.1i)
append(L1,L2,L12) (L1, L2 заданы, L12 - строится) 

Показать, что:
1) имеет размер 4*n + 4*m + 4, 
2) дерево вывода имеет m + 1 вершину, 
3) имеет линейную сложность по длине. 

** Решение


#+begin_src prolog
append([X|Xs], Ys, [X|Zs]) :- append(Xs, Ys, Zs).
append([], Ys, Ys).
#+end_src

*** имеет размер 4*n + 4*m + 4.

append(L1, L2, L12).
\\
m - количество элементов в L1. \\
n - количество элементов в L2.

Размер терма равен количеству символов в его текствовом представлении.
Константы и переменные имеют размер 1. Составной терм имеет размер
на 1 больше ммы размеров его аргументов.

Т.о. список, содержащий n элементов имеет размер n*2 + 1.

Список, составленный из объединения списков длины n и m имеет длину
n + m. Поэтому в нашем случае случе т.к. цель содержит составной терм, аргументы
которого 3 списка длины n, m, и n + m иммем:

(2*n + 1) + (2*m + 1) + (2*(n + m) + 1) + 1 = 4*n + 4*m + 4

*** дерево вывода имеет m + 1 вершину, 

#+begin_src prolog
append([a_1, a_2, a_3, ... a_m], Ys, [a_1|Zs])   | 1
     append([a_2, a_3, ... a_m], Ys, [a_2|Zs])   | 2
          append([a_3, ... a_m], Ys, [a_3|Zs])   | 3
...
              append([a_n | []], Ys, [a_m|Zs])   | m
                      append([], Ys, Ys)         | m + 1
#+end_src

*** имеет линейную сложность по длине. 
   
Дерево вывода для append имеет m узлов => сложность линейно зависит от m.
